import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getLocale} from 'next-intl/server';
import Header from "@/components/header/Header";
import { Vazirmatn } from 'next/font/google';

const vazirmatn = Vazirmatn({
 subsets: ['arabic']
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bime Bazar",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: LayoutProps) => {

  const locale = await getLocale();
  return (
    <html lang={locale} className={vazirmatn.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-[360px] shadow-sm mt-6 relative`}
      >
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
